version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mariadb:latest
    container_name: ai-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=ai-mariadb
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    restart: always


  #service 2: definition of phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    restart: always

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ai-mariadb



  #service 3: definition of spring-boot app
  virtual-labs-be:                        #it is just a name, which will be used only in this file.
    image: virtual-labs-be:dev          #name of the image after dockerfile executes
    container_name: virtual-labs-be       #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8080:8080"                       #docker containter port with your os port
    restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ai-mariadb:3306/teams?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ai-mariadb