###
# Login with admin
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
    if (response.status === 200) {
        client.global.set("auth_token_admin", response.body.token);
    }
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}

###
# Add teacher 'd111111'
POST http://localhost:8080/API/teacher/
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "id": "d111111",
  "lastName": "Malnati",
  "firstName": "Giovanni",
  "email": "d111111@polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Register teacher 'd111111'
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "id": "d111111",
  "lastName": "Malnati",
  "firstName": "Giovanni",
  "password": "pd1",
  "email": "d111111@polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Add teacher 'd222222'
POST http://localhost:8080/API/teacher/
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "id": "d222222",
  "lastName": "Servetti",
  "firstName": "Antonio",
  "email": "d222222@polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Register teacher 'd222222'
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "id": "d222222",
  "lastName": "Servetti",
  "firstName": "Antonio",
  "password": "pd2",
  "email": "d222222@polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Add student 's111111'
POST http://localhost:8080/API/students/
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "id": "s111111",
  "lastName": "Rossi",
  "firstName": "Mario",
  "email": "s111111@studenti.polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Register student 's111111'
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "id": "s111111",
  "lastName": "Rossi",
  "firstName": "Mario",
  "password": "ps1",
  "email": "s111111@studenti.polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Add student 's222222'
POST http://localhost:8080/API/students/
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "id": "s222222",
  "lastName": "Bianchi",
  "firstName": "Giulio",
  "email": "s222222@studenti.polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Register student 's222222'
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "id": "s222222",
  "lastName": "Bianchi",
  "firstName": "Giulio",
  "password": "ps2",
  "email": "s222222@studenti.polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Add student 's333333'
POST http://localhost:8080/API/students/
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "id": "s333333",
  "lastName": "Verdi",
  "firstName": "Giuseppe",
  "email": "s333333@studenti.polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Register student 's333333'
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "id": "s333333",
  "lastName": "Verdi",
  "firstName": "Giuseppe",
  "password": "ps3",
  "email": "s333333@studenti.polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Add student 's444444'
POST http://localhost:8080/API/students/
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "id": "s444444",
  "lastName": "Bruni",
  "firstName": "Giorgio",
  "email": "s444444@studenti.polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Register student 's444444'
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "id": "s444444",
  "lastName": "Bruni",
  "firstName": "Giorgio",
  "password": "ps4",
  "email": "s444444@studenti.polito.it"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Login with teacher1
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "d111111",
  "password": "pd1"
}


> {%
    if (response.status === 200) {
        client.global.set("auth_token_teacher1", response.body.token);
    }
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}

###
# Add course 'c1'
# Hint: should be done by teacher1
POST http://localhost:8080/API/courses/
Content-Type: application/json
Authorization: Bearer {{auth_token_teacher1}}

{
  "name": "c1",
  "min": 3,
  "max": 4
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Add course 'c2'
# Hint: should be done by teacher1
POST http://localhost:8080/API/courses/
Content-Type: application/json
Authorization: Bearer {{auth_token_teacher1}}

{
  "name": "c2",
  "min": 1,
  "max": 2
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Add course 'c3'
# Hint: should be done by teacher1
POST http://localhost:8080/API/courses/
Content-Type: application/json
Authorization: Bearer {{auth_token_teacher1}}

{
  "name": "c3",
  "min": 2,
  "max": 4
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Add and enroll to 'c3' students from CSV
POST http://localhost:8080/API/courses/c3/enrollMany
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token_teacher1}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.csv"

< test.csv
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Login with teacher2
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "d222222",
  "password": "pd2"
}

> {%
    if (response.status === 200) {
        client.global.set("auth_token_teacher2", response.body.token);
    }
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}

###
# Add course 'c4'
# Hint: should be done by teacher2
POST http://localhost:8080/API/courses/
Content-Type: application/json
Authorization: Bearer {{auth_token_teacher2}}

{
  "name": "c4",
  "min": 3,
  "max": 5
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Enroll student 's222222' to 'c4'
POST http://localhost:8080/API/courses/c4/enrollOne
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token_teacher2}}

--WebAppBoundary
Content-Disposition: form-data; name="studentId"

s222222
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Enroll student 's444444' to 'c4'
POST http://localhost:8080/API/courses/c4/enrollOne
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token_teacher2}}

--WebAppBoundary
Content-Disposition: form-data; name="studentId"

s444444
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Add assignment to course 'c4'
# content is "assignment1" encoded to Base64 format
# expiryDate is in UTC with format: "yyyy-mm-ddThh:mm:ss.SSSZ"
# where S are millisecnonds and Z is ISO 8601 time zone
POST http://localhost:8080/API/courses/c4/assignment
Content-Type: application/json
Authorization: Bearer {{auth_token_teacher2}}

{
  "name": "assignment1",
  "content": "YXNzaWdubWVudDE=",
  "expiryDate": "2021-03-14T23:59:59.000+0000"
}
> {%
    if (response.status === 200) {
        client.global.set("assignmentId1", response.body.id);
    }
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Add assignment to course 'c4'
# content is "assignment2" encoded to Base64 format
# expiryDate is in UTC with format: "yyyy-mm-ddThh:mm:ss.SSSZ"
# where S are millisecnonds and Z is ISO 8601 time zone
POST http://localhost:8080/API/courses/c4/assignment
Content-Type: application/json
Authorization: Bearer {{auth_token_teacher2}}

{
  "name": "assignment2",
  "content": "YXNzaWdubWVudDI=",
  "expiryDate": "2021-03-14T23:59:59.000+0000"
}
> {%
    if (response.status === 200) {
        client.global.set("assignmentId2", response.body.id);
    }
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Add assignment to course 'c4'
# content is "assignment3" encoded to Base64 format
# expiryDate is in UTC with format: "yyyy-mm-ddThh:mm:ss.SSSZ"
# where S are millisecnonds and Z is ISO 8601 time zone
POST http://localhost:8080/API/courses/c4/assignment
Content-Type: application/json
Authorization: Bearer {{auth_token_teacher2}}

{
  "name": "assignment3",
  "content": "YXNzaWdubWVudDM=",
  "expiryDate": "2021-03-14T23:59:59.000+0000"
}
> {%
    if (response.status === 200) {
        client.global.set("assignmentId3", response.body.id);
    }
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Login with student2
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "s222222",
  "password": "ps2"
}

> {%
    if (response.status === 200) {
        client.global.set("auth_token_student2", response.body.token);
    }
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}

###
# Submit version for homework of 's222222' of 'assignment1' of 'c4'
# Content is "submitted" encoded to Base64 format
POST http://localhost:8080/API/courses/c4/assignment/{{assignmentId1}}/homework/s222222/submit
Content-Type: application/json
Authorization: Bearer {{auth_token_student2}}

{
  "content": "c3VibWl0dGVk"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Submit version for homework of 's222222' of 'assignment2' of 'c4'
# Content is "submitted" encoded to Base64 format
POST http://localhost:8080/API/courses/c4/assignment/{{assignmentId2}}/homework/s222222/submit
Content-Type: application/json
Authorization: Bearer {{auth_token_student2}}

{
  "content": "c3VibWl0dGVk"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Student 's222222' reads 'assignment3' of 'c4'
GET http://localhost:8080/API/courses/c4/assignment/{{assignmentId3}}
Authorization: Bearer {{auth_token_student2}}

###
# Login with student4
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "s444444",
  "password": "ps4"
}

> {%
    if (response.status === 200) {
        client.global.set("auth_token_student4", response.body.token);
    }
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}

###
# Submit version for homework of 's444444' of 'assignment1' of 'c4'
# Content is "submitted" encoded to Base64 format
POST http://localhost:8080/API/courses/c4/assignment/{{assignmentId1}}/homework/s444444/submit
Content-Type: application/json
Authorization: Bearer {{auth_token_student4}}

{
  "content": "c3VibWl0dGVk"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Submit version for homework of 's444444' of 'assignment2' of 'c4'
# Content is "submitted" encoded to Base64 format
POST http://localhost:8080/API/courses/c4/assignment/{{assignmentId2}}/homework/s444444/submit
Content-Type: application/json
Authorization: Bearer {{auth_token_student4}}

{
  "content": "c3VibWl0dGVk"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Submit review for homework of 's222222' of 'assignment1' of 'c4'
# Content is "no more submit" encoded to Base64 format
# Student can't submit another version
POST http://localhost:8080/API/courses/c4/assignment/{{assignmentId1}}/homework/s222222/review?canReSubmit=false
Content-Type: application/json
Authorization: Bearer {{auth_token_teacher2}}

{
  "content": "bm8gbW9yZSBzdWJtaXQ="
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Submit review for homework of 's444444' of 'assignment1' of 'c4'
# Content is "no more submit" encoded to Base64 format
# Student can't submit another version
POST http://localhost:8080/API/courses/c4/assignment/{{assignmentId1}}/homework/s444444/review?canReSubmit=false
Content-Type: application/json
Authorization: Bearer {{auth_token_teacher2}}

{
  "content": "bm8gbW9yZSBzdWJtaXQ="
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Submit review for homework of 's222222' of 'assignment2' of 'c4'
# Content is "reviewed" encoded to Base64 format
# Student can submit another version
POST http://localhost:8080/API/courses/c4/assignment/{{assignmentId2}}/homework/s222222/review?canReSubmit=true
Content-Type: application/json
Authorization: Bearer {{auth_token_teacher2}}

{
  "content": "cmV2aWV3ZWQ="
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# Set score for homework of 's222222' of 'assignment1' of 'c4'
POST http://localhost:8080/API/courses/c4/assignment/{{assignmentId1}}/homework/s222222/setScore
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token_teacher2}}

--WebAppBoundary
Content-Disposition: form-data; name="score"

30
--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
