POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
if (response.status === 200) {
    client.global.set("auth_token", response.body.token);
}
 %}

###
# Add teacher 'd111111' (teacher1)
# Hint: should be done by admin
POST http://localhost:8080/API/teacher/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "d111111",
  "lastName": "Malnati",
  "firstName": "Giovanni"
}

###
# Add teacher 'd222222' (teacher2)
# Hint: should be done by admin
POST http://localhost:8080/API/teacher/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "d222222",
  "lastName": "Servetti",
  "firstName": "Antonio"
}

###

PUT http://localhost:3000/students/3
Content-Type: application/json

{
  "id": 3,
  "serial": "s333333",
  "lastName": "Verdi",
  "firstName": "Giuseppe",
  "courseId": 1,
  "groupId": 0
}

###

GET http://localhost:3000/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9saXZlckBtYWlsLmNvbSIsImlhdCI6MTU5MTQ4OTg5OSwiZXhwIjoxNTkxNDkzNDk5LCJzdWIiOiIxIn0.XWVXf6kPZG8NfBvcu3Hy2PsbJ4Kn4wicGLYBfCeL-lQ

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "oliver@mail.com",
  "password": "bestPassw0rd"
}