###
# Add course 'Programmazione di Sistema'
# Hint: should be done by teacher1
POST http://localhost:8080/API/courses/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Programmazione di Sistema",
  "min": 3,
  "max": 4
}

###
# Add course 'Applicazioni Internet'
# Hint: should be done by teacher2
POST http://localhost:8080/API/courses/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Applicazioni Internet",
  "min": 1,
  "max": 2
}

###
