###
# Add teacher 'd111111' (teacher1)
# Hint: should be done by admin
POST http://localhost:8080/API/teacher/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "d111111",
  "lastName": "Malnati",
  "firstName": "Giovanni",
  "email": "d111111@polito.it"
}

###
# Add teacher 'd222222' (teacher2)
# Hint: should be done by admin
POST http://localhost:8080/API/teacher/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "d222222",
  "lastName": "Servetti",
  "firstName": "Antonio",
  "email": "d222222@polito.it"
}
